### ISSUE TITLE
Fix test CI with environment variables

### ISSUE THREAD

**Issue by hwakabh** [hwakabh/bennu-official#128]
# AsIs
Visit: https://github.com/hwakabh/bennu-official/pull/127#issuecomment-1913761056
This pipeline failure is because we have added dependencies of object storage, MinIO, in #127 , but we have not provided environmental variables `MINIO_STORAGE_*` yet in Test CI.
This change have also been breaking local compose.yaml starting up, so we have to consider this issue with whole design of local development env & production deployment.

# ToDo
- Fix how we provide object storage store in local environment.
  - It is the best way to create bucket and fetch its API Key and Secret in container startup process
- Update Test CI for fix

# (Optional) Acceptance criteria
Test CI will be passed

# (Optional) Additional contexts
Relates #127

**Comment by hwakabh** [comment]
As we could reproduced this issue on local environment with running `python manage.py test --debug-mode`, this is because of lack of environmental variables, as described above.
After starting MinIO server with creating bucket on docker-compose, confirmed that tests become to pass if we added `MINIO_STORAGE_*` in `local_settings.py`.

Since `local_settings.py` is ignored from Git controlling, in CI we have to add them as environmental variables.

**Comment by hwakabh** [comment]
Finding solutions to starting up MinIO container in docker-compose, with creating default public bucket, there are several ways to solve this.

### Using `minio/minio` image
This is an official image maintained by MinIO, confirmed that we can create default bucket after starting up minio-server with using `minio/mc` image.

```yaml
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minio123
    entrypoint: sh
    command:
      - -c
      - |
        mkdir -p /export/bennu
        minio server /export --console-address :9001
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/bitnami/minio/data
    healthcheck:
      test: "mc ping local --count 1 || exit 1"
      interval: 3s
      retries: 3
    deploy:
      restart_policy:
        condition: on-failure
  mc:
    image: minio/mc:latest
    container_name: mc
    entrypoint: sh
    command:
      - -c
      - |
        mc alias set local http://minio:9000 minioadmin minio123
        mc anonymous set public local/bennu
    depends_on:
      minio:
        condition: service_healthy
```

### Using `bitnami/minio` image
Since this image has some additional features with accepting environmental variables, we can easily create default (multiple) bucket at the container startup with configuring policies.
Also with this image, we have not to create client container to configure default bucket, so this makes our code more cleaner.
As mentioned in the [comment](https://github.com/hwakabh/bennu-official/pull/132#issuecomment-1916167108), considering using of CI, we adopt to this way as our implementation.

```yaml
  minio:
    image: bitnami/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minio123
      MINIO_DEFAULT_BUCKETS: bennu:public
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/bitnami/minio/data
    healthcheck:
      test: "mc ping local --count 1 || exit 1"
      interval: 3s
      retries: 3
    deploy:
      restart_policy:
        condition: on-failure
```
